version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      patch:
        applies-to: version-updates
        update-types:
          - "patch"
      minor:
        applies-to: version-updates
        update-types:
          - "minor"
    commit-message:
      prefix: "[dependabot] composer"

  - package-ecosystem: "docker"
    directory: "/docker/nginx"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[dependabot] nginx"

  - package-ecosystem: "docker"
    directory: "/docker/php"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[dependabot] php"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
        interval: "daily"
