name: outdated

on:
    schedule:
        - cron: '0 7 1 * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  outdated:
    runs-on: ubuntu-latest
    steps:
      - name: Install Just
        uses: extractions/setup-just@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Pulling Docker images
        run: just compose pull
      - name: Building Docker images
        run: just compose build
      - name: Maintain Composer cache
        uses: actions/cache@v5
        with:
          path: .cache/composer
          key: composer-${{ hashFiles('composer.lock') }}
          restore-keys: composer-
      - name: Check for outdated packages
        run: just composer-outdated
