name: security

on:
    schedule:
        - cron: '0 5 1 * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Install Just
        uses: extractions/setup-just@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Pulling Docker images
        run: just compose pull
      - name: Building Docker images
        run: just compose build
      - name: Maintain Composer cache
        uses: actions/cache@v5
        with:
          path: .cache/composer
          key: composer-${{ hashFiles('composer.lock') }}
          restore-keys: composer-
      - name: Install dependencies
        run: just install
      - name: Check security issues
        run: just test-security
